<div class="controls">
    <?= $this->tabs ?>
</div>
<div class="content">
    <h1><?= $this->title ?></h1>

    <h2>Counters</h2>
    <?php foreach($this->counts as $type => $info): ?>
    <h3><?= $this->keywords($type) ?></h3>
    <ul>
    <?php foreach($info as $key => $value): ?>
    <li><strong><?= $this->keywords($key) ?>:</strong> <?= $value ?></li>
    <?php endforeach; ?>
    </ul>
    <?php endforeach; ?>

    <h2>Files</h2>
    <ul>
    <?php foreach($this->files as $file): ?>
        <li><?= $file ?></li>
    <?php endforeach; ?>
    </ul>
</div>
